#on:
#  workflow_run:
#    workflows:
#      - Release
#    types:
#      - completed

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
#    timeout-minutes: 15
    steps:
#      - name: Wait for 10 minutes
#        run: sleep 600
      
      - name: Checkout Homebrew Repository
        uses: actions/checkout@v4
        with:
          repository: test-alp/homebrew-nuget-publish-action
          ref: main
          token: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}
          path: homebrew-repo

      - name: Homebrew Formula Update
        run: |
          version=$(curl https://api.nuget.org/v3-flatcontainer/nugetpublishaction/index.json | jq -r '.versions | last')
          echo $version
          curl -o NugetPublishAction.nupkg https://nuget.org/api/v2/package/NugetPublishAction/$version
          sha256=$(sha256sum NugetPublishAction.nupkg | awk '{print $1}')
          echo $sha256
          cd homebrew-repo
          sed -i "s/^\(\s*sha256\s*\"\)[^\"]*\"/\1$sha256\"/" nuget-publish-action.rb
          sed -i 's|^\(\s*url\s*"\)[^"]*"|\1https://nuget.org/api/v2/package/NugetPublishAction/$version"|' nuget-publish-action.rb
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add nuget-publish-action.rb
          git commit -m "Update $version via GitHub Actions"
          git status
          git push -u origin main
